<!DOCTYPE html>
<html lang="en">
<head>
    <title>
How CLR maps SEH exceptions to managed exception types | .NET Blog - linksfor.dev(s)    </title>
    <meta charset="utf-8">
    <link rel="alternate" type="application/rss+xml" title="Linksfor.dev(s) feed" href="https://linksfor.dev/feed.rss" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google" value="notranslate">
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="How CLR maps SEH exceptions to managed exception types | .NET Blog - linksfor.dev(s)"/>
    <meta property="article:author" content="CLR Team Follow CLR Team"/>
    <meta property="og:description" content="Managed exception handling is built on Windows OS&#x2019;s Structured Exception Handling, commonly referred to as SEH (to learn more about SEH, please read Matt Pietrek&#x2019;s excellent article first). This implies that CLR understands how to interoperate between SEH and managed exception systems,"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://devblogs.microsoft.com/dotnet/how-clr-maps-seh-exceptions-to-managed-exception-types/"/>

<meta property="og:site_name" content="linksfor.dev(s)" />
</head>
<body>
    <div class="grid">
        <h1>
                <span style="cursor: default" title="linksfor.dev(s) has been running for 1 year! :partypopper:">ðŸŽ‰</span>
<a href="/" style="color:inherit">linksfor.dev(s)</a>
        </h1>
        <title>linksfor.dev(s) - How CLR maps SEH exceptions to managed exception types | .NET Blog</title>
<div class="readable">
        <h1>How CLR maps SEH exceptions to managed exception types | .NET Blog</h1>
            <div>by CLR Team Follow CLR Team</div>
            <div>Reading time: 6-7 minutes</div>
        <div>Posted here: 20 Dec 2019</div>
        <p><a href="https://devblogs.microsoft.com/dotnet/how-clr-maps-seh-exceptions-to-managed-exception-types/">https://devblogs.microsoft.com/dotnet/how-clr-maps-seh-exceptions-to-managed-exception-types/</a></p>
        <hr/>
<div id="readability-page-1" class="page"><div id="featured"><div><div><div><div><p><img src="https://devblogs.microsoft.com/dotnet/wp-content/uploads/sites/10/2019/02/Screen-Shot-2019-02-01-at-4.41.42-PM-150x150.png" width="58" height="58" alt="CLR Team"></p><p>CLR Team</p></div></div></div><p>May 14th, 2009</p><p>Managed exception handling is built on Windows OSâ€™s <a href="http://msdn.microsoft.com/en-us/library/ms680657(VS.85).aspx" target="_blank">Structured Exception Handling</a>, commonly referred to as SEH (to learn more about SEH, please read Matt Pietrekâ€™s <a href="http://www.microsoft.com/msj/0197/Exception/Exception.aspx" target="_blank">excellent article</a> first). This implies that CLR understands how to interoperate between SEH and managed exception systems, which is a very key point since SEH is based upon the notion of exception codes, while managed exception handling represents an exception using a managed type. Depending upon how, and by whom, the SEH exception is raised, the CLR accordingly maps it to a managed exception.</p><p><i>Note: The following discussion is focused on the Desktop CLR, which runs on Windows OS. While the idea of the discussion is to help understand the concept, it is illustrated using some implementation details that could change in future.</i></p><br><h3>Synchronous exceptions in managed code</h3><p>When managed code uses the <i>throw </i>keyword to throw an exception, it has already instantiated a managed exception object that will represent the thrown exception. This is passed to the CLR, which sets up some exception related state on the thread and invokes the Kernel32â€™s <a href="http://msdn.microsoft.com/en-us/library/ms680552(VS.85).aspx" target="_blank"><i>RaiseException</i></a><i> </i>API to raise the managed exception. The first argument to this API is the SEH exception code for the exception being raised and the CLR passes <i>0xE0434F4D, </i>the managed exception SEH code.</p><p>At this point, the OS comes into the picture and begins to look for an SEH exception handler on the stack of the thread which raised the exception. The CLR registers one of its functions as an exception handler with the OS, to process exceptions arising out of managed code. When it sees the CLR SEH exception code, it <i>knows </i>that a managed exception is being raised and proceeds to look up the thread state to retrieve exception related details (e.g. identify the managed exception object representing the exception being raised).</p><p>Thus, in the case of synchronous managed throw, it is easy to map the SEH exception to managed exception type.</p><br><h3>Asynchronous exceptions in managed code</h3><p>Asynchronous exceptions, simply put, are the ones which get raised without an explicit throw. This can happen in managed code if you perform arithmetic operations (e.g. divide by zero exception) or use <a href="http://msdn.microsoft.com/en-us/library/t2yzs44b.aspx" target="_blank"><i>unsafe</i></a><i> </i>managed code that could result in exceptions like Access Violation (AV). The interesting thing about asynchronous exceptions is that they are represented using their unique SEH exception code. For example, AV is represented by <i>0xC0000005, </i>divide by zero (integer) is represented by <i>0xC0000094, </i>while divide by zero (floating) is represented by <i>0xC000008E. </i>Common exceptions are listed <a href="http://msdn.microsoft.com/en-us/library/aa363082(VS.85).aspx" target="_blank">here</a> and exception code values can be found in <i>WinNT.h.</i></p><p>When such an exception is raised in managed code, once again the OS begins looking for an exception handler on the stack of the thread where the exception was raised. When CLRâ€™s exception handler is invoked, it <i>understands </i>that the exception in question was not synchronously thrown by managed code since the exception code is not the CLR SEH exception code. Thus, instead of looking up the thread state for exception related details, it proceeds to <i>map </i>the SEH exception to one of the managed exception types. For example, divide by zero exception (both integer and floating point) are represented using <a href="http://msdn.microsoft.com/en-us/library/system.dividebyzeroexception.aspx" target="_blank"><i>System.DivideByZeroException</i></a><i>. </i></p><p>On a similar note, when a real AV is generated in managed code, it has the exception code of <i>0xC0000005. </i>Since managed code has the notion of a <i>null reference, </i>the runtime does few more checks to determine if the AV represents an attempt to use a null reference or not. If it is, then it gets mapped to <a href="http://msdn.microsoft.com/en-us/library/system.nullreferenceexception.aspx" target="_blank"><i>System.NullReferenceException</i></a>. Otherwise, it gets mapped to <a href="http://msdn.microsoft.com/en-us/library/system.accessviolationexception.aspx" target="_blank"><i>System.AccessViolationException</i></a><i> </i>type (in v2.0 and later runtimes).</p><br><h3>Exceptions thrown in native code</h3><p>Another way the CLR gets to see SEH exceptions is when managed code has called into native code using a mechanism like <a href="http://msdn.microsoft.com/en-us/library/ms235282.aspx" target="_blank">Platform Invocation Services</a> (PInvoke for short). In the example below, the stack grows from top to bottom and blue frames represent managed code, while the reddish frame represents native code:</p><p><a href="https://devblogs.microsoft.com/wp-content/uploads/sites/10/2019/02/image_2.png" data-featherlight="image"></a><a href="https://devblogs.microsoft.com/wp-content/uploads/sites/10/2019/02/image_thumb.png" data-featherlight="image"> <img title="image" alt="image" src="https://devblogs.microsoft.com/wp-content/uploads/sites/10/2019/02/image_thumb.png" width="710" height="318"> </a></p><p>Assuming <i>Zoo </i>throws a native exception that is not handled in it, the exception will propagate up the stack, as the OS walks up the stack looking for a potential handler for the exception. In such a case, since the next frame on the stack is <i>Bar</i>, which is managed, the OS ends up calling the CLRâ€™s exception handler. Since the SEH exception comes from native code, it could have <i>any </i>exception code. For instance, it could be a C++ exception (which has the SEH exception code of <i>0xE06D7363</i>) or it could be a SEH exception code specific to the application. The point is that CLR <i>does not </i>know about all the SEH exception codes that exist (and will be created in the future). And only a subset of the existing ones is of interest from the perspective of mapping the code to a specific managed exception type.</p><p>Thus, when the native exception is seen by CLRâ€™s exception handler, it will attempt to map the most common SEH exception codes to their corresponding managed exception type (as explained earlier with some examples). For any other SEH exception code that the runtime does not identify, it gets mapped to the <a href="http://msdn.microsoft.com/en-us/library/system.runtime.interopservices.sehexception.aspx" target="_blank"><i>System.Runtime.InteropServices.SEHException</i></a><i> </i>type.</p><br><h3>Subtleties and what happens next?</h3><p>1) This mapping is done <i>only</i> once when CLRâ€™s exception handler is invoked by the OS (assuming there are no context transitions on the stack) for the first managed frame on the stack from the point of throw of the specific SEH exception.</p><p>2) Since this mapping is done based upon SEH exception codes, the CLR <i>knows </i>if a given managed exception instance represents a real native SEH exception or not. For example, CLR knows if a <i>System.AccessViolationException </i>instance represents a real AV or is a regular managed exception thrown by managed code. Why does this matter? Well, it does when the CLR has determine the <a href="http://msdn.microsoft.com/en-us/magazine/dd419661.aspx" target="_blank">corruption severity</a> of an exception!</p><p>Once the mapping is completed, the CLR begins regular exception handling process of finding a handler for the exception.</p><br><p>â€“ Gaurav Khanna,</p><p>Developer, CLR</p></div></div></div></div>
    </div>
    <footer>
        <div>created by buildstarted &copy; 2020 <a href="/about">about</a></div>
        <div>Share this page on social media: copy and paste this url https://linksfor.dev/</div>
        <div>If you prefer RSS: <a href="https://linksfor.dev/feed.xml">https://linksfor.dev/feed.xml</a></div>
    </footer>
    
</body>
</html>