<!DOCTYPE html>
<html lang="en">
<head>
    <title>
The Throw Keyword was a Mistake - linksfor.dev(s)    </title>
    <meta charset="utf-8">
    <link rel="alternate" type="application/rss+xml" title="Linksfor.dev(s) feed" href="https://linksfor.dev/feed.rss" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google" value="notranslate">
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="The Throw Keyword was a Mistake - linksfor.dev(s)"/>
    <meta property="og:description" content="Exception Handling"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://hackernoon.com/the-throw-keyword-was-a-mistake-l9e532di"/>

<meta property="og:site_name" content="linksfor.dev(s)" />
</head>
<body>
    <div class="devring" style="background: #222">
        <div style="text-align:center">Explore other dev related sites in this ring. If you would like to join this ring <a href="https://devring.club">click here</a>.</div>
        <div class="grid">
            <div style="display: grid; grid-template-columns: .5fr 1fr 1fr 1fr; text-align: center;">
                <span class="devring-title"><a href="https://devring.club/">devring.club</a></span>
                <a href="https://devring.club/sites/1/prev" class="devring-previous">Previous</a>
                <a href="https://devring.club/random" class="devring-random">Random</a>
                <a href="https://devring.club/sites/1/next" class="devring-next">Next</a>
            </div>
        </div>
    </div>
    <div class="grid">
        <h1>
<a href="/" style="color:inherit">linksfor.dev(s)</a>
        </h1>
        <title>linksfor.dev(s) - The Throw Keyword was a Mistake</title>
<div class="readable">
        <h1>The Throw Keyword was a Mistake</h1>
            <div>Reading time: 8-11 minutes</div>
        <div>Posted here: 28 Jan 2020</div>
        <p><a href="https://hackernoon.com/the-throw-keyword-was-a-mistake-l9e532di">https://hackernoon.com/the-throw-keyword-was-a-mistake-l9e532di</a></p>
        <hr/>
<div id="readability-page-1" class="page"><div v-pre="">
          
            
            <p><img src="https://hackernoon.com/drafts/uomg32om.png"></p><p>Decades ago when a program crashed you would see a dire error message</p><p><img src="https://hackernoon.com/photos/uhqELzxApzXNUnEZuMMvKMOZcaP2-vbn132gk" alt=""></p><p>This meant that something horrible had happened. Usually the problem was the software tried to read or write some memory outside its address space. It could mean some other problem; a full disk, a device error, but it was an unrecoverable condition, something that software developers call an&nbsp;<strong>exception</strong>.</p><p>There was only one option: tap the spacebar or use a mouse, and invoke “OK.”</p><p>Why? It’s not OK. You may have just lost two hours of work (that’s your fault. Hit Ctrl-S every few seconds or you deserve to lose it). But this still sucked.</p><p>Exceptions aren’t new. Dealing with them in a more elegant way than inelegantly crashing goes all the way back to 1962 in a near-forgotten language called LISP. See the Resources section for an article on the history.</p><p>Languages in modern programming pulled the better ideas from the diverse implementations of handling exceptions and formed a simple language syntax with a few new keywords, and Structured Exception Handling (SEH) was born.</p><p>The idea was that software developers could trap exceptions and offer a more elegant shutdown than simply crashing and losing everything:</p><div><pre><code><span>try</span>
{
    do_something_unsafe();
}
<span>catch</span>(Exception exception)
{
    save_work();
    apologize(exception);
    <span>exit</span>();
}
</code></pre></div><p>So far so good. Unless the application data was corrupted by the Horrible Event you had a cleaner shutdown and could restart the program and continue.</p><p>And it got better. Not all exceptions meant shutting down; some were recoverable. If the program tried to access forbidden memory it could return to the previous state and continue. Happy days.</p><p>Then some little smarty decided that the operating system shouldn’t have all the fun and that developers should be able to&nbsp;<em>create&nbsp;</em>exception conditions and use this new architecture themselves, and in what is likely one of the worst things to ever happen to software development until pair programming came along, extended the new architecture with</p><p>Calling this new keyword would make the instruction pointer jump to the nearest&nbsp;<strong>catch&nbsp;</strong>block, wherever that may be; exception types were defined so the jump could be to a selected handler. This may have been a well-meant idea, more likely it was just to be orthogonal and provide developers with both ends of the transaction. </p><p>Wise developers; experienced developers; thoughtful developers. Probably nobody ever thought what would happen when they put this catastrophic operation in the hands of less experienced developers.</p><p>And we can’t put the genie back in the bottle.</p><h2>What’s So Special About Exceptions?</h2><p>The point of SEH was EH. Exception handling. Gravely serious conditions. But just as the&nbsp;<strong>return&nbsp;</strong>keyword isn’t restricted to the end of a function,&nbsp;<strong>throw</strong>&nbsp;wasn’t restricted to exceptions. It wasn’t long before developers were using it in error conditions where return codes were more appropriate, like parameter validation. </p><p>And then for conditions that weren’t errors at all. And, inevitably, as a way to save a few minutes of typing. And a lot of these were the same people who compulsively hyper-optimized even the most performance-uncritical code, having no clue that&nbsp;<strong>throw</strong>&nbsp;exacts an enormous penalty.</p><p>Example. Our intrepid short-attention-span test-driven-developer is three levels deep in&nbsp;<strong>void&nbsp;</strong>functions and suddenly discovers a potential error condition. He doesn’t want to “refactor” three&nbsp;<strong>void</strong>&nbsp;functions to return error codes, he has a foosball game with the team in five minutes, so he issues a call to&nbsp;<strong>throw</strong>&nbsp;and wraps the call to the first of the&nbsp;<strong>void</strong>&nbsp;functions in a&nbsp;<strong>try-catch</strong>&nbsp;block and runs off to his game. Facepalm.</p><p>Throwing exceptions<strong>&nbsp;</strong>becomes just another tool in the box, a glorified&nbsp;<strong>longjmp</strong>; why should it be restricted to real exceptions?</p><p>Why indeed.</p><h2>And Then Came Java</h2><p>And in Java&nbsp;<strong>throw&nbsp;</strong>is idiomatic. Java developers are expected to throw routinely. It’s even better than return! Get a bad argument? Throw an exception. Didn’t find a value in an array? Throw an exception.</p><p><strong>Whee.</strong></p><p>Before this, using this sledgehammer of a keyword on a thumbtack of an issue was just bad judgment, Java came along and validated that bad judgment.</p><h2>The Year Everything Crashed</h2><p>Then SEH was added to C++. If you were using computers in the years that followed you remember the time well even if you didn’t know the reason; a lot of software that had been stable and solid before started crashing and misbehaving. In one year iTunes went from unbreakable to almost dangerous to use and you had to save off a copy of your music database or lose it every few days. There was a massive loss of software reliability and if you watched memory in your Task Manager you could see it leaking in torrents.</p><p>Everyone was using&nbsp;<strong>throw&nbsp;</strong>everywhere, and it wasn’t working right. Garbage Collection was far from perfect, far from reliable, and developers using&nbsp;<strong>throw&nbsp;</strong>just expected things to be magically cleaned up. They weren’t.</p><h2>The Performance Penalty</h2><p><strong>Throw&nbsp;</strong>is hugely expensive. Some mobile groups at Microsoft started looking at their profiling data and their faces went white, word went out to people coding on weaker processors to call a halt to the&nbsp;<strong>throw&nbsp;</strong>keyword.</p><p>Processors and RAM have had to stay well ahead of the software running on them because too many developers write inefficient code. New languages had to collect allocated memory, cleaning up after sloppy work because hardly anyone had the discipline to properly manage memory (I remember a Microsoft division meeting where a David Stockman clone sagaciously told us that memory leaks were a fact of life). Rather than cultivate discipline the languages had to add toilet paper functionality.</p><p>With&nbsp;<strong>throw&nbsp;</strong>this problem was squared and cubed.</p><h2>Control Flow</h2><p>Going all the way back to the earliest high-level languages we have had approximately the same constructs:<strong>&nbsp;if/else, while, for</strong>; functions with entrances and exits. Code could be analyzed, its behavior clearly deterministic, every path could be enumerated and every condition examined. This is control flow. Good developers could find bugs without a debugger, just reading the code.</p><h2>Not Anymore</h2><p>Yes&nbsp;<strong>throw&nbsp;</strong>is expensive in CPU cycles, but that’s not the real problem.&nbsp;<strong>Throw&nbsp;</strong>added a second system logic of control flow, disconnected from the usual one, unpredictable, hybridized and intertwined. Code using both could not be reliably analyzed, not by human eyes. Not unless the scope of&nbsp;<strong>throw</strong>&nbsp;and&nbsp;<strong>catch</strong>&nbsp;were very tightly and carefully constructed and if you think most developers are going to do that then you haven’t worked with many average ones.</p><p>One early large Java project was subject to analysis with advanced tools and found to have an astounding 13,000 ambiguous code paths based on thrown exceptions; the behavior of the code was massively unpredictable.</p><p>What we&nbsp;<em>can&nbsp;</em>predict, and with certainty, is that developers are&nbsp;<em>not&nbsp;</em>going to write with the rigor required to use this keyword safely. Software development is disintegrating before our eyes; focus and concentration are deprecated and just as inefficient code is mitigated by ever faster processors, increasingly sloppy work is mitigated by an obsessive shift of focus from development to testing.</p><p>People can’t enter a flow state anymore, not when their day starts with a slog of a commute to attend a daily scrum and they are interrupted all day by meetings and open office conversations. It’s not possible to rise above mediocrity when you can’t concentrate and software companies are more concerned with team cohesion than with quality work.</p><p>And it’s in this world that we have this horrible keyword with its wholly unpredictable behavior.</p><h2>The Impossible Dream</h2><p>If I had my way</p><ul><li>the keyword would be removed from all languages that use it</li><li>only the language runtime and operating system would be allowed to raise exceptions</li></ul><p>That isn’t going to happen; most projects would break. They would have to be rewritten.</p><h2>Within Our Grasp</h2><p>Languages with SEH should have a compiler option of not recognizing <strong>throw&nbsp;</strong>so it cannot be used. Barring that,&nbsp;<strong>development leads should forbid its use</strong>. The mobile groups did so. Some languages already designate API that throw, calls to these API should be rigorously wrapped in&nbsp;<em>local</em>&nbsp;<strong>try-catch</strong>&nbsp;blocks,&nbsp;<strong>at the same scope as the exception-throwing API</strong>, with a global catch around everything, or perhaps nested ones, solely to find unhandled throw conditions and patch them. Software is ready when the outer handlers are never hit. Outside the small local blocks the control flow returns to deterministic predictability.</p><p>This preserves the original intent; programs don’t crash so much and recovery is possible. Software development goes back to being a deterministic endeavor and we regain some stability, probably lot of stability.</p><p>Don’t use&nbsp;<strong>throw</strong>. Just stop. Stop now.</p>
          
          
          
          

          

          
        </div></div></div>
    </div>
    <footer>
        <div>created by buildstarted &copy; 2020 <a href="/about">about</a></div>
        <div>Share this page on social media: copy and paste this url https://linksfor.dev/</div>
        <div>If you prefer RSS: <a href="https://linksfor.dev/feed.xml">https://linksfor.dev/feed.xml</a></div>
        <div>Customer satisfaction guaranteed to be optional.</div>
    </footer>
    
    <script async defer>
        _dna = window._dna || {};
        _dna.siteId = "linksfor.devs";
        _dna.outlink = true;

        (function () {
            let dna = document.createElement('script');
            dna.type = 'text/javascript';
            dna.async = true;
            dna.src = '//dna.buildstarted.com/t.js';
            let s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(dna, s);
        })();
    </script>
    <noscript><img src="//dna.buildstarted.com/g?siteId=linksfor.devs" /></noscript>
</body>
</html>